name: Build and Deploy to EKS 
 
on: 
  push: 
    branches: [main] 
    paths: 
      - 'orders-service/**' 
      - 'products-service/**' 
      - 'k8s/**' 
  workflow_dispatch:   # adds a manual "Run workflow" button too 
 
permissions: 
  id-token: write   # required for OIDC token issuance 
  contents: read 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    strategy: 
      matrix: 
        service: [orders-service, products-service] 

    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 
 
      - name: Login to ECR 
        uses: aws-actions/amazon-ecr-login@v2 
 
      - name: Build, tag, push image 
        run: | 
          docker build -t 075992502789.dkr.ecr.ap-south-1.amazonaws.com/microservice-eks-demo-app:${{ matrix.service }}-${{ github.sha }} ./${{ matrix.service }} 
          docker push 075992502789.dkr.ecr.ap-south-1.amazonaws.com/microservice-eks-demo-app:${{ matrix.service }}-${{ github.sha }} 
 
      - name: Set up kubeconfig 
        run: aws eks update-kubeconfig --region ap-south-1 --name microservice-eks-demo 
 
      - name: Substitute image and apply manifests 
        run: | 
          DEPLOYMENT_FILE="k8s/${{ matrix.service == 'orders-service' && 'deployment-orders' || 'deployment-products' }}.yaml"
          sed -i "s|IMAGE_PLACEHOLDER|075992502789.dkr.ecr.ap-south-1.amazonaws.com/microservice-eks-demo-app:${{ matrix.service }}-${{ github.sha }}|g" $DEPLOYMENT_FILE
          kubectl apply -f $DEPLOYMENT_FILE --validate=false
          kubectl apply -f k8s/ingress.yaml --validate=false
          kubectl rollout status deployment/${{ matrix.service }} --timeout=120s 
 
      - name: Deploy new image 
        run: | 
          kubectl set image deployment/${{ matrix.service }} \
            ${{ matrix.service == 'orders-service' && 'orders' || 'products' }}=075992502789.dkr.ecr.ap-south-1.amazonaws.com/microservice-eks-demo-app:${{ matrix.service }}-${{ github.sha }} 
          kubectl rollout status deployment/${{ matrix.service }} --timeout=90s
